# Generated by Django 4.1.7 on 2023-04-11 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='address', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дарег',
                'verbose_name_plural': 'Дарег',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='posts', verbose_name='Фото')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Жарыя',
                'verbose_name_plural': 'Жарыялар',
            },
        ),
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Айыл чарбасы',
                'verbose_name_plural': 'Айыл чарбасы',
            },
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory', models.PositiveIntegerField(verbose_name='Жалпы территориясы')),
                ('number_of_villages', models.PositiveIntegerField(verbose_name='Айылдардын саны')),
                ('number_of_smokes', models.PositiveIntegerField(verbose_name='Түтүндөрдүн саны')),
                ('avg_learn', models.PositiveIntegerField(verbose_name='Атайын орто билим  берүү')),
                ('licey', models.PositiveIntegerField(verbose_name='Лицей')),
                ('teacher_number', models.PositiveIntegerField(verbose_name='Мугалимдердин саны')),
                ('students_number', models.PositiveIntegerField(verbose_name='Тарбиялануучу балдардын саны')),
                ('ogan', models.PositiveIntegerField(verbose_name='Ооган согушунун ардагерлери')),
                ('chernobyl', models.PositiveIntegerField(verbose_name='Чернобыль кырсыгына катышкандар')),
                ('hospital', models.PositiveIntegerField(verbose_name='Ооруканалар')),
                ('family_medicine', models.PositiveIntegerField(verbose_name='Үй-бүлөлүк дарыгерлер')),
                ('fap', models.PositiveIntegerField(verbose_name='ФАП')),
                ('apteka', models.PositiveIntegerField(verbose_name='Аптекалар')),
                ('railroad', models.PositiveIntegerField(verbose_name='Жакынкы темир жол')),
                ('airport', models.PositiveIntegerField(verbose_name='Жакынкы аэропорт')),
                ('district', models.PositiveIntegerField(verbose_name='Райондун борборуна чейинки аралык')),
                ('region', models.PositiveIntegerField(verbose_name='Облустун борборуна чейинки аралык')),
                ('sea', models.PositiveIntegerField(verbose_name='Дениз деңгээлинен бийиктиги')),
            ],
            options={
                'verbose_name': 'Жалпы малыматтар',
                'verbose_name_plural': 'Жалпы малыматтар',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маданият',
                'verbose_name_plural': 'Маданият',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='gallery', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Галлерея',
                'verbose_name_plural': 'Галлерея',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('img', models.FileField(upload_to='info', verbose_name='Фото')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Маалымат',
                'verbose_name_plural': 'Маалыматтар',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='posts/img', verbose_name='Фото')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Основной текст')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Жанылык',
                'verbose_name_plural': 'Жанылыктар',
            },
        ),
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок заявления')),
                ('file', models.FileField(upload_to='resolve', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Токтом',
                'verbose_name_plural': 'Токтомдор',
            },
        ),
        migrations.CreateModel(
            name='CulturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='culture')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='AgriCulturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='culture')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agriculture')),
            ],
        ),
    ]
