# Generated by Django 4.1.7 on 2023-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq_remove_agriculturephoto_culture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoninfo',
            options={'verbose_name': 'Жалпы маалыматтар', 'verbose_name_plural': 'Жалпы маалыматтар'},
        ),
    ]
