# Generated by Django 4.1.7 on 2023-04-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Жаңылык', 'verbose_name_plural': 'Жаңылыктар'},
        ),
    ]
