# Generated by Django 4.1.7 on 2023-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gallery_options_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='sub_title',
            field=models.CharField(default='', max_length=256, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
