# Generated by Django 4.1.7 on 2023-04-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_information_sub_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Пресса', 'verbose_name_plural': 'Пресса'},
        ),
    ]
